### ISSUE TITLE
command for formatting GSE detail tsv into OMOP tables

### ISSUE THREAD

**Issue by ngiangre** [NCBI-Codeathons/OMOPOmics#2]
`perl output_tables.pl GSE60682_details.tsv` doesn't work. Can you write out the command so we can put it in the implementation section? Thanks!

**Comment by anishchakka** [comment]
All my output files are written to a folder `output/`. I'm modifying my code to include creating a folder called output/.

**Comment by ngiangre** [comment]
Sorry anish, but can you modify your code to output the tables to the OMOP_tables directory? Have a variable with the destination and then use that variable for where to output the tables. The idea in my head is to have omop formatted tables in a directory, which we named OMOP_tables. Also, and you can add this, have that table in the data folder since technically these would be data. Is that ok with you? Let me know your thoughts!

**Comment by anishchakka** [comment]
No problem! 

Introduced a variable for output directory. Can you take a look and let me know if this looks OK?

**Comment by ngiangre** [comment]
Great thanks!
